"""empty message

Revision ID: 1d904618f596
Revises: 7572e10686d1
Create Date: 2021-08-23 09:29:46.448629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d904618f596'
down_revision = '7572e10686d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_received_posts_received_post'), ['received_post'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_received_posts_received_post'))

    # ### end Alembic commands ###
