"""user, subreddit, and keyword table to mysql

Revision ID: 51adf011e82e
Revises: 71bf6bfe008e
Create Date: 2021-06-08 16:38:37.697385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51adf011e82e'
down_revision = '71bf6bfe008e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keywords_keyword'), ['keyword'], unique=False)

    op.create_table('subreddits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subreddit_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subreddits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subreddits_subreddit_name'), ['subreddit_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('phone_num', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone_num'), ['phone_num'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('subreddits_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subreddit_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subreddit_id', 'keyword_id', name='UC_subreddit_id_keyword_id')
    )
    op.create_table('users_subreddits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subreddit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_subreddits')
    op.drop_table('subreddits_keywords')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_phone_num'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('subreddits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subreddits_subreddit_name'))

    op.drop_table('subreddits')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_keyword'))

    op.drop_table('keywords')
    # ### end Alembic commands ###