"""created subreddits and keywords schema

Revision ID: 6305390e2fe2
Revises: d6bb2e35c0a5
Create Date: 2020-12-14 15:19:09.025772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6305390e2fe2'
down_revision = 'd6bb2e35c0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subreddit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subreddit_name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subreddit_subreddit_name'), 'subreddit', ['subreddit_name'], unique=True)
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=True),
    sa.Column('subreddit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_keyword'), 'keyword', ['keyword'], unique=True)
    op.add_column('user', sa.Column('phone_num', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_phone_num'), 'user', ['phone_num'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone_num'), table_name='user')
    op.drop_column('user', 'phone_num')
    op.drop_index(op.f('ix_keyword_keyword'), table_name='keyword')
    op.drop_table('keyword')
    op.drop_index(op.f('ix_subreddit_subreddit_name'), table_name='subreddit')
    op.drop_table('subreddit')
    # ### end Alembic commands ###
