"""empty message

Revision ID: 6c891a84b11c
Revises: 4f387cc3cf19
Create Date: 2021-07-09 12:55:16.106244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c891a84b11c'
down_revision = '4f387cc3cf19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subreddits_keywords', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'subreddits', ['subreddit_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users_subreddits', schema=None) as batch_op:
        batch_op.drop_constraint('users_subreddits_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_subreddits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_subreddits_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('subreddits_keywords', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###