"""added unique constraint to subreddits_keywords association table.

Revision ID: 71bf6bfe008e
Revises: 9db57a797a4d
Create Date: 2021-01-18 11:06:15.747420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bf6bfe008e'
down_revision = '9db57a797a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subreddits_keywords', schema=None) as batch_op:
        batch_op.create_unique_constraint('UC_subreddit_id_keyword_id', ['subreddit_id', 'keyword_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subreddits_keywords', schema=None) as batch_op:
        batch_op.drop_constraint('UC_subreddit_id_keyword_id', type_='unique')

    # ### end Alembic commands ###