"""empty message

Revision ID: 75c2df820a91
Revises: eb006837913a
Create Date: 2021-07-08 16:01:27.256585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75c2df820a91'
down_revision = 'eb006837913a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received_posts', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_received_posts'), ['received_posts'], unique=True)
        batch_op.drop_index('ix_users_sent_posts_queue')
        batch_op.drop_column('sent_posts_queue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_posts_queue', mysql.VARCHAR(length=128), nullable=True))
        batch_op.create_index('ix_users_sent_posts_queue', ['sent_posts_queue'], unique=True)
        batch_op.drop_index(batch_op.f('ix_users_received_posts'))
        batch_op.drop_column('received_posts')

    # ### end Alembic commands ###