"""empty message

Revision ID: eb006837913a
Revises: c4b1f646aef3
Create Date: 2021-07-08 15:04:37.767290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb006837913a'
down_revision = 'c4b1f646aef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_posts_queue', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_sent_posts_queue'), ['sent_posts_queue'], unique=True)
        batch_op.drop_index('ix_users_submission_queue')
        batch_op.drop_column('submission_queue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_queue', mysql.VARCHAR(length=128), nullable=True))
        batch_op.create_index('ix_users_submission_queue', ['submission_queue'], unique=True)
        batch_op.drop_index(batch_op.f('ix_users_sent_posts_queue'))
        batch_op.drop_column('sent_posts_queue')

    # ### end Alembic commands ###