export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const SUBMIT_SUBREDDIT_INFO = 'SUBMIT_SUBREDDIT_INFO';
export const SUBMIT_SUBREDDIT_INFO_FAIL = 'SUBMIT_SUBREDDIT_INFO_FAIL';
export const FETCH_SUBREDDITS = 'FETCH_SUBREDDITS';
export const FETCH_SUBREDDITS_FAIL = 'FETCH_SUBREDDITS_FAIL';
